# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b8abb696c7e82488ae3fb77733e6eb07b7aa480cd3f5ce4986c592fc576a51f4a3473eca6d1f3c0fb9378fcbd90e1ba37fa3dcf07da8e4b7bb13551f1076310

test:
  secret_key_base: 44bd5525fac989042d1b204ec646ab61b7d29bc85b2e57090ce19f66a10946a751b532bf62f9ea682c18d83a9f902c1fe02801cb3d0247e2add930e4463118de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
